
  CREATE TABLE "INT"."CLIENT"
   (	"AMND_STATE" VARCHAR2(1 CHAR) DEFAULT 'A',
	"AMND_DATE" DATE DEFAULT sysdate,
	"AMND_OFFICER" NUMBER(18,0),
	"AMND_PREV" NUMBER(18,0),
	"ID" NUMBER(18,0) NOT NULL ENABLE,
	"F_I" NUMBER(18,0),
	"BRANCH" VARCHAR2(32 CHAR),
	"CCAT" VARCHAR2(1 CHAR),
	"CLT" NUMBER(18,0),
	"PCAT" VARCHAR2(1 CHAR),
	"SERVICE_GROUP" VARCHAR2(32 CHAR),
	"SHORT_NAME" VARCHAR2(255 CHAR),
	"TITLE" NUMBER(18,0),
	"SALUTATION_SUFFIX" VARCHAR2(32 CHAR),
	"FIRST_NAM" VARCHAR2(255 CHAR),
	"LAST_NAM" VARCHAR2(255 CHAR),
	"FATHER_S_NAM" VARCHAR2(255 CHAR),
	"BIRTH_NAM" VARCHAR2(255 CHAR),
	"MOTHER_S_NAM" VARCHAR2(255 CHAR),
	"BIRTH_DATE" DATE,
	"BIRTH_PLACE" VARCHAR2(255 CHAR),
	"GENDER" VARCHAR2(1 CHAR),
	"ENABLE_AFFILIATION" VARCHAR2(1 CHAR),
	"AFFILIATION_TYPE" VARCHAR2(32 CHAR),
	"AFFILIATED_WITH" NUMBER(18,0),
	"MARITAL_STATUS" NUMBER(18,0),
	"COMPANY_NAM" VARCHAR2(255 CHAR),
	"TRADE_NAM" VARCHAR2(255 CHAR),
	"COMPANY_DEPARTMENT" VARCHAR2(255 CHAR),
	"CLIENT_NUMBER" VARCHAR2(64 CHAR),
	"REG_NUMBER_TYPE" VARCHAR2(32 CHAR),
	"REG_NUMBER" VARCHAR2(64 CHAR),
	"REG_DETAILS" VARCHAR2(255 CHAR),
	"ITN" VARCHAR2(64 CHAR),
	"SOCIAL_NUMBER" VARCHAR2(64 CHAR),
	"TAX_POSITION" VARCHAR2(32 CHAR),
	"PROFESSION" VARCHAR2(255 CHAR),
	"LANGUAGE" NUMBER(18,0),
	"CITIZENSHIP" VARCHAR2(3 CHAR),
	"DATE_EXPIRE" DATE,
	"DATE_OPEN" DATE DEFAULT sysdate,
	"TR_TITLE" NUMBER(18,0),
	"TR_FIRST_NAM" VARCHAR2(32 CHAR),
	"TR_LAST_NAM" VARCHAR2(32 CHAR),
	"COUNTRY" VARCHAR2(3 CHAR),
	"ADDRESS_ZIP" VARCHAR2(32 CHAR),
	"STATE" VARCHAR2(32 CHAR),
	"CITY" VARCHAR2(255 CHAR),
	"ADDRESS_LINE_1" VARCHAR2(255 CHAR),
	"ADDRESS_LINE_2" VARCHAR2(255 CHAR),
	"ADDRESS_LINE_3" VARCHAR2(255 CHAR),
	"ADDRESS_LINE_4" VARCHAR2(255 CHAR),
	"PHONE" VARCHAR2(32 CHAR),
	"PHONE_H" VARCHAR2(32 CHAR),
	"PHONE_M" VARCHAR2(32 CHAR),
	"FAX" VARCHAR2(32 CHAR),
	"FAX_H" VARCHAR2(32 CHAR),
	"E_MAIL" VARCHAR2(255 CHAR),
	"URL" VARCHAR2(255 CHAR),
	"DELIVERY_TYPE" NUMBER(18,0),
	"TR_COMPANY_NAM" VARCHAR2(32 CHAR),
	"ADD_DATE_01" DATE,
	"ADD_DATE_02" DATE,
	"ADD_INFO_01" VARCHAR2(3900 CHAR),
	"ADD_INFO_02" VARCHAR2(3900 CHAR),
	"ADD_INFO_03" VARCHAR2(3900 CHAR),
	"ADD_INFO_04" VARCHAR2(3900 CHAR),
	"IS_READY" VARCHAR2(1 CHAR) DEFAULT 'N'
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL KEEP FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
   CACHE
  CREATE UNIQUE INDEX "INT"."PK_CLIENT" ON "INT"."CLIENT" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 65536
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  GLOBAL PARTITION BY HASH ("ID")
 (PARTITION "SYS_P58678" NOCOMPRESS
  TABLESPACE "USERS" ,
 PARTITION "SYS_P58679" NOCOMPRESS
  TABLESPACE "USERS" ,
 PARTITION "SYS_P58680" NOCOMPRESS
  TABLESPACE "USERS" ,
 PARTITION "SYS_P58681" NOCOMPRESS
  TABLESPACE "USERS" ,
 PARTITION "SYS_P58682" NOCOMPRESS
  TABLESPACE "USERS" ,
 PARTITION "SYS_P58683" NOCOMPRESS
  TABLESPACE "USERS" ,
 PARTITION "SYS_P58684" NOCOMPRESS
  TABLESPACE "USERS" ,
 PARTITION "SYS_P58685" NOCOMPRESS
  TABLESPACE "USERS" )
ALTER TABLE "INT"."CLIENT" ADD CONSTRAINT "PK_CLIENT" PRIMARY KEY ("ID")
  USING INDEX "INT"."PK_CLIENT"  ENABLE


  CREATE TABLE "INT"."ACNT_CONTRACT"
   (	"AMND_DATE" DATE DEFAULT sysdate,
	"AMND_STATE" VARCHAR2(1 CHAR) DEFAULT 'A',
	"AMND_OFFICER" NUMBER(18,0),
	"AMND_PREV" NUMBER(18,0),
	"ID" NUMBER(18,0) NOT NULL ENABLE,
	"PCAT" VARCHAR2(1 CHAR),
	"CON_CAT" VARCHAR2(1 CHAR),
	"TERMINAL_CATEGORY" VARCHAR2(1 CHAR),
	"CCAT" VARCHAR2(1 CHAR),
	"F_I" NUMBER(18,0),
	"BRANCH" VARCHAR2(32 CHAR),
	"SERVICE_GROUP" VARCHAR2(32 CHAR),
	"CONTRACT_NUMBER" VARCHAR2(64 CHAR),
	"BASE_RELATION" VARCHAR2(255 CHAR),
	"CONTRACT_NAME" VARCHAR2(255 CHAR),
	"COMMENT_TEXT" VARCHAR2(255 CHAR),
	"RELATION_TAG" VARCHAR2(1 CHAR),
	"ACNT_CONTRACT__ID" NUMBER(18,0),
	"CONTR_TYPE" NUMBER(18,0),
	"CONTR_SUBTYPE__ID" NUMBER(18,0),
	"SERV_PACK__ID" NUMBER(18,0),
	"ACC_SCHEME__ID" NUMBER(18,0),
	"OLD_PACK" NUMBER(18,0),
	"CHANNEL" VARCHAR2(32 CHAR),
	"OLD_SCHEME" NUMBER(18,0),
	"PRODUCT" VARCHAR2(32 CHAR),
	"PARENT_PRODUCT" VARCHAR2(32 CHAR),
	"PRODUCT_PREV" VARCHAR2(32 CHAR),
	"MAIN_PRODUCT" NUMBER(18,0),
	"LIAB_CATEGORY" VARCHAR2(1 CHAR),
	"CLIENT__ID" NUMBER(18,0),
	"CLIENT_TYPE" NUMBER(18,0),
	"ACNT_CONTRACT__OID" NUMBER(18,0),
	"LIAB_CONTRACT" NUMBER(18,0),
	"LIAB_CONTRACT_PREV" NUMBER(18,0),
	"BILLING_CONTRACT" NUMBER(18,0),
	"BEHAVIOR_GROUP" NUMBER(18,0),
	"BEHAVIOR_TYPE" NUMBER(18,0),
	"BEHAVIOR_TYPE_PREV" NUMBER(18,0),
	"CHECK_AVAILABLE" VARCHAR2(1 CHAR),
	"CHECK_USAGE" VARCHAR2(1 CHAR) DEFAULT 'N',
	"CURR" VARCHAR2(3 CHAR),
	"OLD_CURR" VARCHAR2(3 CHAR),
	"AUTH_LIMIT_AMOUNT" NUMBER(28,10) DEFAULT 0 NOT NULL ENABLE,
	"BASE_AUTH_LIMIT" NUMBER(28,10) DEFAULT 0 NOT NULL ENABLE,
	"LIAB_BALANCE" NUMBER(28,10) DEFAULT 0 NOT NULL ENABLE,
	"LIAB_BLOCKED" NUMBER(28,10) DEFAULT 0 NOT NULL ENABLE,
	"OWN_BALANCE" NUMBER(28,10) DEFAULT 0 NOT NULL ENABLE,
	"OWN_BLOCKED" NUMBER(28,10) DEFAULT 0 NOT NULL ENABLE,
	"SUB_BALANCE" NUMBER(28,10) DEFAULT 0 NOT NULL ENABLE,
	"SUB_BLOCKED" NUMBER(28,10) DEFAULT 0 NOT NULL ENABLE,
	"TOTAL_BLOCKED" NUMBER(28,10) DEFAULT 0 NOT NULL ENABLE,
	"TOTAL_BALANCE" NUMBER(28,10) DEFAULT 0 NOT NULL ENABLE,
	"SHARED_BALANCE" NUMBER(28,10) DEFAULT 0 NOT NULL ENABLE,
	"SHARED_BLOCKED" NUMBER(28,10) DEFAULT 0 NOT NULL ENABLE,
	"AMOUNT_AVAILABLE" NUMBER(28,10) DEFAULT 0 NOT NULL ENABLE,
	"DATE_OPEN" DATE,
	"DATE_EXPIRE" DATE,
	"LAST_BILLING_DATE" DATE,
	"NEXT_BILLING_DATE" DATE,
	"LAST_SCAN" DATE,
	"CARD_EXPIRE" VARCHAR2(4 CHAR),
	"PRODUCTION_STATUS" VARCHAR2(1 CHAR),
	"RBS_MEMBER_ID" VARCHAR2(32 CHAR),
	"RBS_NUMBER" VARCHAR2(64 CHAR),
	"REPORT_TYPE" VARCHAR2(32 CHAR),
	"MAX_PIN_ATTEMPTS" NUMBER(3,0) DEFAULT 3 NOT NULL ENABLE,
	"PIN_ATTEMPTS" NUMBER(3,0) DEFAULT 0 NOT NULL ENABLE,
	"RISK_SCHEME" NUMBER(18,0),
	"CHIP_SCHEME" NUMBER(18,0),
	"RISK_FACTOR" NUMBER(7,3) DEFAULT 1 NOT NULL ENABLE,
	"RISK_FACTOR_PREV" NUMBER(7,3) DEFAULT 1 NOT NULL ENABLE,
	"CONTR_STATUS" NUMBER(18,0),
	"MERCHANT_ID" VARCHAR2(255 CHAR),
	"TR_TITLE" NUMBER(18,0),
	"TR_COMPANY" VARCHAR2(32 CHAR),
	"TR_COUNTRY" VARCHAR2(3 CHAR),
	"TR_FIRST_NAM" VARCHAR2(32 CHAR),
	"TR_LAST_NAM" VARCHAR2(32 CHAR),
	"TR_SIC" VARCHAR2(4 CHAR),
	"ADD_INFO_01" VARCHAR2(255 CHAR),
	"ADD_INFO_02" VARCHAR2(255 CHAR),
	"ADD_INFO_03" VARCHAR2(255 CHAR),
	"ADD_INFO_04" VARCHAR2(255 CHAR),
	"CONTRACT_LEVEL" VARCHAR2(255 CHAR),
	"EXT_DATA" VARCHAR2(4000 CHAR),
	"REPORT_ADDRESS" NUMBER(18,0),
	"SHARE_BALANCE" VARCHAR2(1 CHAR),
	"IS_MULTYCURRENCY" VARCHAR2(1 CHAR),
	"ENABLES_ITEM" VARCHAR2(1 CHAR),
	"CYCLE_LENGTH" NUMBER(3,0) DEFAULT 0 NOT NULL ENABLE,
	"INTERVAL_TYPE" VARCHAR2(1 CHAR) DEFAULT 'M',
	"STATUS_CATEGORY" VARCHAR2(1 CHAR),
	"LIMIT_IS_ACTIVE" VARCHAR2(1 CHAR),
	"ROUTING_IDT" VARCHAR2(32 CHAR),
	"IS_READY" VARCHAR2(1 CHAR) DEFAULT 'N',
	"SETTLEMENT_TYPE" VARCHAR2(1 CHAR),
	"AUTH_SEQ_N" NUMBER(18,0),
	"APPLY_DT" DATE,
	"LOCAL_VERSION" NUMBER(9,0) DEFAULT 0 NOT NULL ENABLE,
	"REMOTE_VERSION" NUMBER(9,0) DEFAULT 0 NOT NULL ENABLE,
	 CONSTRAINT "FK_ACC_SCHEME__ACN" FOREIGN KEY ("ACC_SCHEME__ID")
	  REFERENCES "INT"."ACC_SCHEME" ("ID") ENABLE,
	 CONSTRAINT "FK_ACNT_C__BALANCE" FOREIGN KEY ("ACNT_CONTRACT__OID")
	  REFERENCES "INT"."ACNT_CONTRACT" ("ID") ON DELETE CASCADE ENABLE,
	 CONSTRAINT "FK_CLIENT__CONTRAC" FOREIGN KEY ("CLIENT__ID")
	  REFERENCES "INT"."CLIENT" ("ID") ENABLE,
	 CONSTRAINT "FK_CONTR_SUBTYPE__" FOREIGN KEY ("CONTR_SUBTYPE__ID")
	  REFERENCES "INT"."CONTR_SUBTYPE" ("ID") ENABLE,
	 CONSTRAINT "FK_SERV_PACK_ACNT" FOREIGN KEY ("SERV_PACK__ID")
	  REFERENCES "INT"."SERV_PACK" ("ID") ENABLE
   ) PCTFREE 12 PCTUSED 40 INITRANS 6 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 65536
  PCTINCREASE 0
  BUFFER_POOL KEEP FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
  PARTITION BY LIST ("AMND_STATE")
  SUBPARTITION BY LIST ("ROUTING_IDT")
 (PARTITION "ACTIVE"  VALUES ('A')
PCTFREE 12 PCTUSED 40 INITRANS 6 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 65536
  PCTINCREASE 0
  BUFFER_POOL KEEP FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
 ( SUBPARTITION "OTHER"  VALUES (default) SEGMENT CREATION IMMEDIATE
  STORAGE(
  BUFFER_POOL KEEP FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
 NOCOMPRESS ) ,
 PARTITION "INACTIVE"  VALUES (default)
PCTFREE 12 PCTUSED 40 INITRANS 6 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 65536
  PCTINCREASE 0
  BUFFER_POOL RECYCLE FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
 ( SUBPARTITION "SYS_SUBP57989"  VALUES (DEFAULT) SEGMENT CREATION IMMEDIATE
  STORAGE(
  BUFFER_POOL RECYCLE FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
 NOCOMPRESS ) )  ENABLE ROW MOVEMENT
   CACHE
  CREATE UNIQUE INDEX "INT"."PK_ACNT_CONTRACT" ON "INT"."ACNT_CONTRACT" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 65536
  PCTINCREASE 0
  BUFFER_POOL KEEP FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  GLOBAL PARTITION BY HASH ("ID")
 (PARTITION "SYS_P58646" NOCOMPRESS
  TABLESPACE "USERS" ,
 PARTITION "SYS_P58647" NOCOMPRESS
  TABLESPACE "USERS" ,
 PARTITION "SYS_P58648" NOCOMPRESS
  TABLESPACE "USERS" ,
 PARTITION "SYS_P58649" NOCOMPRESS
  TABLESPACE "USERS" ,
 PARTITION "SYS_P58650" NOCOMPRESS
  TABLESPACE "USERS" ,
 PARTITION "SYS_P58651" NOCOMPRESS
  TABLESPACE "USERS" ,
 PARTITION "SYS_P58652" NOCOMPRESS
  TABLESPACE "USERS" ,
 PARTITION "SYS_P58653" NOCOMPRESS
  TABLESPACE "USERS" )
ALTER TABLE "INT"."ACNT_CONTRACT" ADD CONSTRAINT "PK_ACNT_CONTRACT" PRIMARY KEY
("ID")
  USING INDEX "INT"."PK_ACNT_CONTRACT"  ENABLE


  CREATE TABLE "INT"."ADDRESS_TYPE"
   (	"AMND_STATE" VARCHAR2(1 CHAR) DEFAULT 'A',
	"AMND_DATE" DATE DEFAULT sysdate,
	"AMND_OFFICER" NUMBER(18,0),
	"AMND_PREV" NUMBER(18,0),
	"ID" NUMBER(18,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(255 CHAR),
	"CODE" VARCHAR2(32 CHAR),
	"GROUP_CODE" VARCHAR2(32 CHAR),
	"STANDBY_ADDR_TYPE" NUMBER(18,0),
	"USE_CLIENT_DEFAULT" VARCHAR2(1 CHAR),
	"ADD_INFO" VARCHAR2(3900 CHAR)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
  CREATE UNIQUE INDEX "INT"."PK_ADDRESS_TYPE" ON "INT"."ADDRESS_TYPE" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
ALTER TABLE "INT"."ADDRESS_TYPE" ADD CONSTRAINT "PK_ADDRESS_TYPE" PRIMARY KEY ("
ID")
  USING INDEX "INT"."PK_ADDRESS_TYPE"  ENABLE


  CREATE TABLE "INT"."AFFILIATION_TYPE"
   (	"AMND_DATE" DATE DEFAULT sysdate,
	"AMND_STATE" VARCHAR2(1 CHAR) DEFAULT 'A',
	"AMND_OFFICER" NUMBER(18,0),
	"AMND_PREV" NUMBER(18,0),
	"ID" NUMBER(18,0) NOT NULL ENABLE,
	"CODE" VARCHAR2(32 CHAR),
	"NAME" VARCHAR2(255 CHAR),
	"AFFILIATION_OBJECT_TYPE" VARCHAR2(1 CHAR),
	"GROUP_CODE" VARCHAR2(32 CHAR),
	"RIGHTS_SET" VARCHAR2(32 CHAR),
	"ADD_DATA" VARCHAR2(4000 CHAR)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
  CREATE UNIQUE INDEX "INT"."PK_AFFILIATION_TYPE" ON "INT"."AFFILIATION_TYPE" ("
ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
ALTER TABLE "INT"."AFFILIATION_TYPE" ADD CONSTRAINT "PK_AFFILIATION_TYPE" PRIMAR
Y KEY ("ID")
  USING INDEX "INT"."PK_AFFILIATION_TYPE"  ENABLE


  CREATE TABLE "INT"."APPL_PRODUCT"
   (	"AMND_STATE" VARCHAR2(1 CHAR) DEFAULT 'A',
	"AMND_DATE" DATE DEFAULT sysdate,
	"AMND_OFFICER" NUMBER(18,0),
	"AMND_PREV" NUMBER(18,0),
	"ID" NUMBER(18,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(255 CHAR),
	"CODE" VARCHAR2(32 CHAR),
	"CODE_2" VARCHAR2(32 CHAR),
	"CODE_3" VARCHAR2(32 CHAR),
	"INTERNAL_CODE" VARCHAR2(32 CHAR),
	"F_I" NUMBER(18,0),
	"CCAT" VARCHAR2(1 CHAR),
	"CLIENT_TYPE" NUMBER(18,0),
	"PCAT" VARCHAR2(1 CHAR),
	"CON_CAT" VARCHAR2(1 CHAR),
	"CONTR_TYPE" NUMBER(18,0),
	"CONTR_SUBTYPE" NUMBER(18,0),
	"BASE_RELATION" VARCHAR2(255 CHAR),
	"CHECK_AVAILABLE" VARCHAR2(1 CHAR),
	"CHECK_USAGE" VARCHAR2(1 CHAR),
	"LIAB_CATEGORY" VARCHAR2(1 CHAR),
	"ACC_SCHEME" NUMBER(18,0),
	"MAX_CREDIT_LIMIT" NUMBER(28,10) DEFAULT 0 NOT NULL ENABLE,
	"MIN_CREDIT_LIMIT" NUMBER(28,10) DEFAULT 0 NOT NULL ENABLE,
	"DEFAULT_CREDIT_LIMIT" NUMBER(28,10) DEFAULT 0 NOT NULL ENABLE,
	"REPORT_TYPE" VARCHAR2(32 CHAR),
	"SERV_PACK_TYPE" NUMBER(18,0),
	"SERVICE_PACK" NUMBER(18,0),
	"SCORING_MODEL" NUMBER(18,0),
	"TARIFF_DOMAIN" NUMBER(18,0),
	"TARIFF_DOMAIN_TEMPLATE" NUMBER(18,0),
	"COPY_FROM_PRODUCT" NUMBER(18,0),
	"BASE_PRODUCT" NUMBER(18,0),
	"CUSTOM_DATA" VARCHAR2(4000 CHAR),
	"IS_ACTIVE" VARCHAR2(1 CHAR),
	"DATE_FROM" DATE,
	"DATE_TO" DATE,
	"N_CONTRACTS" NUMBER(3,0) DEFAULT 0 NOT NULL ENABLE,
	"APPL_PRODUCT__OID" NUMBER(18,0),
	"PARENT_CODE" VARCHAR2(32 CHAR),
	"REPORTING_PRODUCT" NUMBER(18,0),
	"MAIN_PRODUCT" NUMBER(18,0),
	"APPL_PR_GROUP__ID" NUMBER(18,0),
	"PRODUCT_GROUP" VARCHAR2(32 CHAR),
	"PRODUCT_STATUS" VARCHAR2(1 CHAR) DEFAULT 'A',
	"CONTRACT_ROLE" VARCHAR2(32 CHAR),
	"ICON" VARCHAR2(255 CHAR),
	"PRODUCT_TEMPLATE" NUMBER(18,0),
	"DATE_SCHEME" NUMBER(18,0),
	"IS_READY" VARCHAR2(1 CHAR) DEFAULT 'N',
	 CONSTRAINT "FK_APPL_PRODUCT__G" FOREIGN KEY ("APPL_PR_GROUP__ID")
	  REFERENCES "INT"."APPL_PR_GROUP" ("ID") ENABLE,
	 CONSTRAINT "FK_APPL_PRODUCT__P" FOREIGN KEY ("APPL_PRODUCT__OID")
	  REFERENCES "INT"."APPL_PRODUCT" ("ID") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
  CREATE UNIQUE INDEX "INT"."PK_APPL_PRODUCT" ON "INT"."APPL_PRODUCT" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
ALTER TABLE "INT"."APPL_PRODUCT" ADD CONSTRAINT "PK_APPL_PRODUCT" PRIMARY KEY ("
ID")
  USING INDEX "INT"."PK_APPL_PRODUCT"  ENABLE


  CREATE TABLE "INT"."BRANCH"
   (	"AMND_STATE" VARCHAR2(1 CHAR) DEFAULT 'A',
	"AMND_DATE" DATE DEFAULT sysdate,
	"AMND_OFFICER" NUMBER(18,0),
	"AMND_PREV" NUMBER(18,0),
	"ID" NUMBER(18,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(255 CHAR),
	"CODE" VARCHAR2(32 CHAR),
	"F_I" NUMBER(18,0),
	"BRANCH__OID" NUMBER(18,0),
	"LIAB_CONTRACT" NUMBER(18,0),
	"UNIT" NUMBER(18,0),
	"BANK_CLIENT" NUMBER(18,0),
	"TIME_ZONE" NUMBER(9,0),
	"UNIT_TYPE" VARCHAR2(32 CHAR),
	 CONSTRAINT "BRANCH__PARENT" FOREIGN KEY ("BRANCH__OID")
	  REFERENCES "INT"."BRANCH" ("ID") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
  CREATE UNIQUE INDEX "INT"."PK_BRANCH" ON "INT"."BRANCH" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
ALTER TABLE "INT"."BRANCH" ADD CONSTRAINT "PK_BRANCH" PRIMARY KEY ("ID")
  USING INDEX "INT"."PK_BRANCH"  ENABLE


  CREATE TABLE "INT"."CLIENT_TITLE"
   (	"AMND_STATE" VARCHAR2(1 CHAR) DEFAULT 'A',
	"AMND_DATE" DATE DEFAULT sysdate,
	"AMND_OFFICER" NUMBER(18,0),
	"AMND_PREV" NUMBER(18,0),
	"ID" NUMBER(18,0) NOT NULL ENABLE,
	"CODE" VARCHAR2(32 CHAR),
	"NAME" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
  CREATE UNIQUE INDEX "INT"."PK_CLIENT_TITLE" ON "INT"."CLIENT_TITLE" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
ALTER TABLE "INT"."CLIENT_TITLE" ADD CONSTRAINT "PK_CLIENT_TITLE" PRIMARY KEY ("
ID")
  USING INDEX "INT"."PK_CLIENT_TITLE"  ENABLE


  CREATE TABLE "INT"."CLIENT_TYPE"
   (	"AMND_DATE" DATE DEFAULT sysdate,
	"AMND_STATE" VARCHAR2(1 CHAR) DEFAULT 'A',
	"AMND_OFFICER" NUMBER(18,0),
	"AMND_PREV" NUMBER(18,0),
	"ID" NUMBER(18,0) NOT NULL ENABLE,
	"CODE" VARCHAR2(32 CHAR),
	"NAME" VARCHAR2(255 CHAR),
	"F_I" NUMBER(18,0),
	"PCAT" VARCHAR2(1 CHAR),
	"CCAT" VARCHAR2(1 CHAR),
	"RESIDENCE" VARCHAR2(1 CHAR)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
  CREATE UNIQUE INDEX "INT"."PK_CLIENT_TYPE" ON "INT"."CLIENT_TYPE" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
ALTER TABLE "INT"."CLIENT_TYPE" ADD CONSTRAINT "PK_CLIENT_TYPE" PRIMARY KEY ("ID
")
  USING INDEX "INT"."PK_CLIENT_TYPE"  ENABLE


  CREATE TABLE "INT"."COUNTRY"
   (	"AMND_DATE" DATE DEFAULT sysdate,
	"AMND_STATE" VARCHAR2(1 CHAR) DEFAULT 'A',
	"AMND_OFFICER" NUMBER(18,0),
	"AMND_PREV" NUMBER(18,0),
	"ID" NUMBER(18,0) NOT NULL ENABLE,
	"AREA_DFLT" NUMBER(18,0),
	"CODE" VARCHAR2(3 CHAR),
	"CODE_2" VARCHAR2(2 CHAR),
	"CURR_CODE" VARCHAR2(3 CHAR),
	"CURR_NAME" VARCHAR2(32 CHAR),
	"CUSTOM_CODE" VARCHAR2(32 CHAR),
	"DEFAULT_LANGUAGE" NUMBER(18,0),
	"LIMIT_CODE" VARCHAR2(32 CHAR),
	"NAME" VARCHAR2(255 CHAR),
	"N_CODE" VARCHAR2(3 CHAR),
	"N_CURR_CODE" VARCHAR2(3 CHAR),
	"POSTAL_CODE" VARCHAR2(32 CHAR),
	"USE_IN_BANK" VARCHAR2(1 CHAR),
	"COUNTRY_OBJECT__ID" NUMBER(18,0),
	"CALENDAR_TYPE" NUMBER(18,0)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
  CREATE UNIQUE INDEX "INT"."PK_COUNTRY" ON "INT"."COUNTRY" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
ALTER TABLE "INT"."COUNTRY" ADD CONSTRAINT "PK_COUNTRY" PRIMARY KEY ("ID")
  USING INDEX "INT"."PK_COUNTRY"  ENABLE


  CREATE TABLE "INT"."CURRENCY"
   (	"AMND_STATE" VARCHAR2(1 CHAR) DEFAULT 'A',
	"AMND_DATE" DATE DEFAULT sysdate,
	"AMND_OFFICER" NUMBER(18,0),
	"AMND_PREV" NUMBER(18,0),
	"ID" NUMBER(18,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(3 CHAR),
	"CODE" VARCHAR2(3 CHAR),
	"FULL_NAME" VARCHAR2(32 CHAR),
	"EXPONENT" VARCHAR2(1 CHAR) DEFAULT '2',
	"FX_RANGE" VARCHAR2(3 CHAR) DEFAULT '1-1',
	"USE_IN_BANK" VARCHAR2(1 CHAR)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
  CREATE UNIQUE INDEX "INT"."PK_CURRENCY" ON "INT"."CURRENCY" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
ALTER TABLE "INT"."CURRENCY" ADD CONSTRAINT "PK_CURRENCY" PRIMARY KEY ("ID")
  USING INDEX "INT"."PK_CURRENCY"  ENABLE


  CREATE TABLE "INT"."LANG"
   (	"AMND_DATE" DATE DEFAULT sysdate,
	"AMND_OFFICER" NUMBER(18,0),
	"AMND_PREV" NUMBER(18,0),
	"AMND_STATE" VARCHAR2(1 CHAR) DEFAULT 'A',
	"CODE" VARCHAR2(3 CHAR),
	"CODE_2" VARCHAR2(2 CHAR),
	"COUNTRY_CODE2" VARCHAR2(2 CHAR),
	"NAME" VARCHAR2(32 CHAR),
	"ID" NUMBER(18,0) NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
  CREATE UNIQUE INDEX "INT"."PK_LANG" ON "INT"."LANG" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
ALTER TABLE "INT"."LANG" ADD CONSTRAINT "PK_LANG" PRIMARY KEY ("ID")
  USING INDEX "INT"."PK_LANG"  ENABLE


  CREATE TABLE "INT"."MARITAL_STATUS"
   (	"AMND_STATE" VARCHAR2(1 CHAR) DEFAULT 'A',
	"AMND_DATE" DATE DEFAULT sysdate,
	"AMND_OFFICER" NUMBER(18,0),
	"AMND_PREV" NUMBER(18,0),
	"ID" NUMBER(18,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(255 CHAR),
	"CODE" VARCHAR2(32 CHAR)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
  CREATE UNIQUE INDEX "INT"."PK_MARITAL_STATUS" ON "INT"."MARITAL_STATUS" ("ID")

  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
ALTER TABLE "INT"."MARITAL_STATUS" ADD CONSTRAINT "PK_MARITAL_STATUS" PRIMARY KE
Y ("ID")
  USING INDEX "INT"."PK_MARITAL_STATUS"  ENABLE


  CREATE TABLE "INT"."SALUTATION"
   (	"AMND_STATE" VARCHAR2(1 CHAR) DEFAULT 'A',
	"AMND_DATE" DATE DEFAULT sysdate,
	"AMND_OFFICER" NUMBER(18,0),
	"AMND_PREV" NUMBER(18,0),
	"ID" NUMBER(18,0) NOT NULL ENABLE,
	"NAME" VARCHAR2(255 CHAR),
	"CODE" VARCHAR2(32 CHAR)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
  CREATE UNIQUE INDEX "INT"."PK_SALUTATION" ON "INT"."SALUTATION" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
ALTER TABLE "INT"."SALUTATION" ADD CONSTRAINT "PK_SALUTATION" PRIMARY KEY ("ID")

  USING INDEX "INT"."PK_SALUTATION"  ENABLE

