SET LONG 20000
SET PAGESIZE 0
SET LINESIZE 2000
SET FEEDBACK OFF
SET ECHO OFF
SET TERMOUT OFF
SET TRIMSPOOL ON

SPOOL project_ddl.sql

SELECT DBMS_METADATA.GET_DDL('TABLE', 'CLIENT') FROM DUAL;
SELECT DBMS_METADATA.GET_DDL('TABLE', 'ACNT_CONTRACT') FROM DUAL;
SELECT DBMS_METADATA.GET_DDL('TABLE', 'ADDRESS_TYPE') FROM DUAL;
SELECT DBMS_METADATA.GET_DDL('TABLE', 'AFFILIATION_TYPE') FROM DUAL;
SELECT DBMS_METADATA.GET_DDL('TABLE', 'APPL_PRODUCT') FROM DUAL;
SELECT DBMS_METADATA.GET_DDL('TABLE', 'BRANCH') FROM DUAL;
SELECT DBMS_METADATA.GET_DDL('TABLE', 'CLIENT_TITLE') FROM DUAL;
SELECT DBMS_METADATA.GET_DDL('TABLE', 'CLIENT_TYPE') FROM DUAL;
SELECT DBMS_METADATA.GET_DDL('TABLE', 'COUNTRY') FROM DUAL;
SELECT DBMS_METADATA.GET_DDL('TABLE', 'CURRENCY') FROM DUAL;
SELECT DBMS_METADATA.GET_DDL('TABLE', 'LANG') FROM DUAL;
SELECT DBMS_METADATA.GET_DDL('TABLE', 'MARITAL_STATUS') FROM DUAL;
SELECT DBMS_METADATA.GET_DDL('TABLE', 'SALUTATION') FROM DUAL;

SPOOL OFF
EXIT
