server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:oracle:thin:@//10.145.48.97:1521/way4db
    username: INTN
    password: way4
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  jackson:
    default-property-inclusion: non_null

soap:
  webservice:
    url: http://localhost:8081/ws
    connect-timeout: 10000
    read-timeout: 30000

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE